# Generated by Django 5.2.4 on 2025-07-31 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('icon_url', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('points', models.IntegerField(default=10)),
                ('category', models.CharField(choices=[('reading', 'Reading'), ('books', 'Books'), ('social', 'Social'), ('other', 'Other')], default='other', max_length=20)),
                ('requirement', models.JSONField(help_text='JSON with requirements for achievement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='achievements.achievement')),
            ],
        ),
    ]
