# Generated by Django 4.2.21 on 2025-08-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('READING', 'Reading'), ('BOOKS', 'Books'), ('SOCIAL', 'Social'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
