# Generated by Django 4.2.21 on 2025-08-03 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_vote_count_bookvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_book_of_week',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WeeklyBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('week_end', models.DateField()),
                ('votes_at_selection', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_selections', to='books.book')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('week_start', 'week_end')},
            },
        ),
    ]
