# Generated by Django 4.2.21 on 2025-08-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_is_book_of_week_weeklybook'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='death_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='gutenberg_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
