# Generated by Django 4.2.21 on 2025-08-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='source_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='source_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
