# Generated by Django 4.2.21 on 2025-08-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_source_id_book_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingprogress',
            name='current_page',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='readingprogress',
            name='total_pages',
            field=models.IntegerField(default=1),
        ),
    ]
